[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_source = 'source ~/.vim/scripts/plugins/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/scripts/plugins/neocomplete.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/config/plugins/deoplete.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'InsertEnter'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = 'source ~/.vim/scripts/plugins/vimtex.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'jsx', 'javascript.jsx', 'javascript', 'tsx', 'typescript.jsx', 'typescript', 'eruby', 'xhtml', 'php', 'twig']
hook_source = 'source ~/.vim/scripts/plugins/emmet-vim.vim'

# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# for vim-jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# React JSX
[[plugins]]
repo = 'mxw/vim-jsx'
depends = ['vim-javascript']
on_ft = ['jsx', 'javascript.jsx']

# React snippets
[[plugins]]
repo = 'justinj/vim-react-snippets'
on_ft = 'javascript.jsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'ymyzk/vim-copl'
on_ft = 'copl'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
on_ft = 'php'

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = 'php'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

