---
- hosts: localhost
  connection: local
  become: no

  roles:
    - role: zzet.rbenv
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.6.5
        rubies:
          - version: 2.6.5
            env:
              RUBY_CONFIGURE_OPTS: "--with-readline-dir=/usr/local/opt/readline/ --with-openssl-dir=/usr/local/opt/openssl/"
      rbenv_users:
        - "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
      default_gems_file: "{{ lookup('env', 'DOTPATH') }}/ansible/default-gems"
