---
- hosts: localhost
  connection: local
  become: no

  vars:
    node_version: 16.13.0

  tasks:

    - name: Install node
      shell: bash -l -c ". ~/.bashrc && nodenv install {{ node_version }}"

    - name: Set default node version
      shell: bash -l -c ". ~/.bashrc && nodenv global {{ node_version }}"

    - name: Install global packages
      npm:
        name: "{{ item }}"
        global: yes
        executable: /Users/{{ ansible_user_id }}/.nodenv/versions/{{ node_version }}/bin/npm
      with_items:
        - aws-cdk
        - gtop
        - npm
        - typescript
        - yarn
