---
- hosts: localhost
  connection: local
  become: yes

  vars:
    texlive_bin: /usr/local/texlive/2020/bin/x86_64-darwin
    texmf_local_dir: /usr/local/texlive/texmf-local/tex/latex/local

  tasks:
    - name: Clear log file
      file:
        state: absent
        path: logs/tlmgr.log

    - name: Update TeX packages
      shell: |
        {{ texlive_bin }}/tlmgr update --self --all 2>&1 | tee -a logs/tlmgr.log

    - name: Download jlistings
      shell: |
        WORKING_DIR=/Users/{{ ansible_user_id }}/tmp
        TARGET_DIR={{ texmf_local_dir }}

        mkdir -p $WORKING_DIR
        cd $WORKING_DIR
        wget https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2
        bunzip2 jlisting.sty.bz2
        cp $WORKING_DIR/jlisting.sty $TARGET_DIR
        {{ texlive_bin }}/mktexlsr
      args:
        creates: "{{ texmf_local_dir }}/jlisting.sty"

    - name: Reflect updates
      shell: |
        cd `{{ texlive_bin }}/kpsewhich -var-value=TEXMFLOCAL`
        {{ texlive_bin }}/mktexlsr
