# -*- mode: ruby -*-
# vi: set ft=ruby :

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Automate deployment, configuration, and upgrading
brew "ansible"
# GNU compiler collection
brew "gcc"
# High performance message passing library
brew "open-mpi"
# Optimized BLAS library
brew "openblas"
# Routines to solve large scale eigenvalue problems
brew "arpack"
# Utility to check whether MAC addresses are already taken on a LAN
brew "arping"
# Record and share terminal sessions
brew "asciinema"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Searches a binary image for embedded files and executable code
brew "binwalk"
# Interface bandwidth monitor
brew "bmon"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c"
# Collection of portable C++ source libraries
brew "boost"
# Freely available high-quality data compressor
brew "bzip2"
# CloudFlare's PKI toolkit
brew "cfssl"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Dependency Manager for PHP
brew "composer"
# Reimplementation of ctags(1)
brew "ctags"
# Distributed search & analytics engine
brew "elasticsearch"
# GNU Emacs text editor
brew "emacs", link: false
# Interpreter for PostScript and PDF
brew "ghostscript", link: false
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# C routines to compute the Discrete Fourier Transform
brew "fftw"
# WebDriver <-> Marionette proxy
brew "geckodriver"
# C++ geography library
brew "geographiclib"
# Geometry Engine
brew "geos"
# Remote repository management made easy
brew "ghq"
# Access GitHub's .gitignore boilerplates
brew "gibo"
# GIF image/animation creator/editor
brew "gifsicle"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Powerful, lightweight programming language
brew "lua"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# SDK for Groovy: a Java-based scripting language
brew "groovysdk"
# File format designed to store large amounts of data
brew "hdf5"
# Improved top (interactive process viewer)
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Display an interface's bandwidth usage
brew "iftop"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli", link: false
# The Kubernetes package manager
brew "kubernetes-helm"
# Next-gen compiler infrastructure
brew "llvm"
# Java-based project management
brew "maven"
# Scalable distributed version control system
brew "mercurial"
# Cross platform, open source .NET development framework
brew "mono"
# Open source relational database management system
brew "mysql", restart_service: true
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Network Kanji code conversion Filter (NKF)
brew "nkf"
# Fast updates of QR and Cholesky decompositions
brew "qrupdate"
# High-level interpreted language for numerical computing
brew "octave"
# The OCaml package manager
brew "opam"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Simplistic interactive filtering tool
brew "peco"
# General-purpose scripting language
brew "php"
# Check coding standards in PHP, JavaScript and CSS
brew "php-code-sniffer"
# Tool to automatically fix PHP coding standards issues
brew "php-cs-fixer"
# General-purpose scripting language
brew "php@7.1"
# Object-relational database system
brew "postgresql"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Show ps output as a tree
brew "pstree"
# x86 and PowerPC Emulator
brew "qemu"
# Software environment for statistical computing
brew "r"
# Persistent key-value database, with built-in net interface
brew "redis"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# The Rust toolchain installer
brew "rustup-init"
# Build tool for Scala projects
brew "sbt"
# JVM-based programming language
brew "scala"
# Generate ASCII art with terminal, shell, and OS info
brew "screenfetch"
# Browser automation for testing purposes
brew "selenium-server-standalone"
# HTTP regression testing and benchmarking utility
brew "siege"
# Generate clients, server stubs, and docs from an OpenAPI spec
brew "swagger-codegen"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Command-line client for Travis CI
brew "travis"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Run Windows applications without a copy of Microsoft Windows
brew "wine"
# View colored diff with side by side and auto pager support
brew "ydiff"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
cask "adobe-acrobat-reader"
cask "alfred"
cask "angry-ip-scanner"
cask "atom"
cask "chromedriver"
cask "chromium"
cask "clipy"
cask "cyberduck"
cask "docker"
cask "dropbox"
cask "duet"
cask "emacs"
cask "firefox"
cask "font-myrica"
cask "gimp"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "inkscape"
cask "intellij-idea-ce"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "java8"
cask "kite"
cask "mactex"
cask "maczip4win"
cask "mendeley"
cask "minikube"
cask "nteract"
cask "postman"
cask "rstudio"
cask "sequel-pro"
cask "skim"
cask "skype"
cask "slack"
cask "sourcetree"
cask "the-unarchiver"
cask "thunderbird"
cask "typora"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "vnc-viewer"
cask "wireshark"
cask "xquartz"
