---
- hosts: localhost
  connection: local
  become: no

  tasks:

    - name: Update homebrew itself first
      homebrew:
        update_homebrew: yes

    - name: Install fundamental brew packages first
      homebrew:
        name:
          - tmux
          - vim
          - zsh
        state: present

    - name: Install fundamental brew cask packages first
      homebrew_cask:
        name:
          - alfred
          - clipy
          - google-backup-and-sync
          - google-chrome
          - google-japanese-ime
          - istat-menus
          - iterm2
          - visual-studio-code
        state: present

    - name: Install homebrew packages using homebrew-bundle
      shell: brew bundle 2>&1 | tee logs/brew_bundle.log

    - name: Link gcc
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - src: /usr/local/bin/gcc-9
          dest: /usr/local/bin/gcc
        - src: /usr/local/bin/g++-9
          dest: /usr/local/bin/g++
        - src: /usr/local/bin/c++-9
          dest: /usr/local/bin/c++

    - name: Link iTerm2 config file
      file:
        src: ~/dotfiles/iterm/profiles.json
        dest: ~/Library/Application Support/iTerm2/DynamicProfiles/profiles.json
        state: link

  handlers:
    - name: Run fc-cache
      shell: fc-cache -vf
