---
- hosts: localhost
  connection: local
  become: no

  vars:
    pyenv_root: "{{ '~/.pyenv' | expanduser }}"
    python_version: anaconda3-5.3.1

  pre_tasks:

    - name: Check if pyenv_root exists
      stat:
        path: "{{ pyenv_root }}"
      register: p

  roles:
    - role: suzuki-shunsuke.pyenv
      when: p.stat.isdir is not defined
    - role: suzuki-shunsuke.pyenv-virtualenv
    - role: suzuki-shunsuke.pyenv-module

  tasks:

    - name: pyenv install anaconda
      pyenv:
        subcommand: install
        version: "{{ python_version }}"
        pyenv_root: "{{ pyenv_root }}"

    - name: pyenv global
      pyenv:
        subcommand: global
        versions:
          - "{{ python_version }}"

    - set_fact: ansible_python_interpreter={{ pyenv_root }}/shims/python

    - name: pip install
      pip:
        executable: "{{ pyenv_root }}/shims/pip"
        name:
          - autopep8
          - chainer
          - dvc
          - flake8
          - flake8-docstrings
          - hacking
          - ipykernel
          - jedi
          - jupyter
          - Keras
          - matplotlib
          - opencv-python
          - pandas
          - pep8
          - pynvim
          - pytest
          - scapy
          - scikit-image
          - scikit-learn
          - scipy
          - setuptools
          - statsmodels
          - tensorflow
          - tqdm
